[cache]
 host = "localhost:6379"
 password = ""
 DB = 0

[common]
 log_dir = "<LOGPATH>/logs"
 data_dir = "<LOGPATH>/data"
 debug = false 
 host_prefix = "https://kilonova.ro/"

[database]
 dbname = "kilonova"
 host = "/var/run/postgresql"
 sslmode = "disable"
 user = "LOCALUSER"

[eval]
 isolatePath = "/tmp/isolate"
 compilePath = "/tmp/kncompiles"
 address = "localhost:8001"

[languages]
 [languages.c]
  disabled = false
  extensions = [".c"]
  is_compiled = true
  Printable = "C"
  compile_command = ["gcc", "-std=c11", "-O2", "-s", "-static", "/box/main.c", "-o", "/box/output"]
  run_command = ["/box/output"]
  source_name = "/box/main.c"
  compiled_name = "/box/output"

  [[languages.c.mounts]]
   in = "/etc"
   out = ""
   opts = ""
   removes = false
 [languages.cpp]
  disabled = false
  extensions = [".cpp", ".c++", ".cc", ".cxx"]
  is_compiled = true
  Printable = "C++"
  compile_command = ["g++", "-std=c++11", "-O2", "-s", "-static", "/box/main.cpp", "-o", "/box/output"]
  run_command = ["/box/output"]
  source_name = "/box/main.cpp"
  compiled_name = "/box/output"

  [[languages.cpp.mounts]]
   in = "/etc"
   out = ""
   opts = ""
   removes = false
 [languages.golang]
  disabled = false
  extensions = [".go"]
  is_compiled = true
  Printable = "Go"
  compile_command = ["go", "build", "/main.go"]
  run_command = ["/main"]
  source_name = "/main.go"
  compiled_name = "/main"
  [languages.golang.build_env]
   GOCACHE = "/go/cache"
   GOPATH = "/go"
  [languages.golang.common_env]
   GOMAXPROCS = "1"
 [languages.haskell]
  disabled = true
  extensions = [".hs", ".lhs"]
  is_compiled = true
  Printable = "Haskell"
  compile_command = ["ghc", "-o", "/box/output", "/box/main.hs"]
  run_command = ["/box/output"]
  source_name = "/box/main.hs"
  compiled_name = "/box/output"
 [languages.java]
  disabled = true
  extensions = [".java"]
  is_compiled = true
  Printable = "Java"
  compile_command = ["javac", "/Main.java"]
  run_command = ["java", "Main"]
  source_name = "/Main.java"
  compiled_name = "/Main.class"

  [[languages.java.mounts]]
   in = "/etc"
   out = ""
   opts = ""
   removes = false
 [languages.python]
  disabled = false
  extensions = [".py", ".py3"]
  is_compiled = false
  Printable = "Python 3"
  run_command = ["python3", "/box/main.py"]
  source_name = "/box/main.py"
  compiled_name = "/box/main.py"

[email]
 host = "HOST"
 username = "USERNAME"
 password = "PASSWORD"
