version: "3"
services:
    kilonova:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./data:/data:Z
            - ./:/app:Z
            - /sys/fs/cgroup:/sys/fs/cgroup
        restart: always
        depends_on:
            - db
        privileged: true
    db:
        image: postgres:12.2
        volumes:
            - ./sqldata:/var/lib/postgresql/data:Z
        environment:
            POSTGRES_USER: kilonova
            POSTGRES_PASSWORD: kn_password
            POSTGRES_DB: kilonova
        restart: always
